nodes:
  # 互联网服务提供商节点
  - name: "北京电信"
    ip: "182.18.87.102"
    location: "北京"
    isp: "电信"
    port: 80
  
  - name: "北京移动"
    ip: "183.242.5.249"
    location: "北京"
    isp: "移动"
    port: 80

  - name: "北京联通"
    ip: "182.48.101.102"
    location: "北京"
    isp: "联通"
    port: 80 