name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true  # 启用 Go 模块缓存
      
      - name: Go Build Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Build Binaries
        run: |
          mkdir -p build
          # 并行构建以提高速度
          go build -v -o build/cfspeedtest_${GITHUB_REF_NAME}_windows_amd64.exe
          go build -v -o build/cfspeedtest_${GITHUB_REF_NAME}_linux_amd64
          go build -v -o build/cfspeedtest_${GITHUB_REF_NAME}_darwin_amd64
      
      - name: Prepare Release Files
        run: |
          cp -r configs build/
          cp ip.txt LICENSE README.md build/
      
      - name: Create Archives
        run: |
          cd build
          zip -r cfspeedtest_${GITHUB_REF_NAME}_windows_amd64.zip cfspeedtest_${GITHUB_REF_NAME}_windows_amd64.exe configs/ ip.txt LICENSE README.md
          tar czf cfspeedtest_${GITHUB_REF_NAME}_linux_amd64.tar.gz cfspeedtest_${GITHUB_REF_NAME}_linux_amd64 configs/ ip.txt LICENSE README.md
          tar czf cfspeedtest_${GITHUB_REF_NAME}_darwin_amd64.tar.gz cfspeedtest_${GITHUB_REF_NAME}_darwin_amd64 configs/ ip.txt LICENSE README.md
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.zip
            build/*.tar.gz
          body_path: release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
