name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
            suffix: .exe
          - os: linux
            arch: amd64
            suffix: ""
          - os: darwin
            arch: amd64
            suffix: ""

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true
      
      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          mkdir -p build
          go build -v -o build/cfspeedtest_${GITHUB_REF_NAME}_${{ matrix.os }}_${{ matrix.arch }}${{ matrix.suffix }}
          cp -r configs build/
          cp ip.txt LICENSE README.md build/
          cd build
          if [ "${{ matrix.os }}" = "windows" ]; then
            zip -r cfspeedtest_${GITHUB_REF_NAME}_${{ matrix.os }}_${{ matrix.arch }}.zip *
          else
            tar czf cfspeedtest_${GITHUB_REF_NAME}_${{ matrix.os }}_${{ matrix.arch }}.tar.gz *
          fi
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: build/*.*

  create-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: builds
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*.zip
            artifacts/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
